require 'htmlentities'
require 'pry'

MUSIC_QUESTIONS=
[{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which band had hits in 1972 with the songs &quot;Baby I&#039;m A Want You&quot;, &quot;Everything I Own&quot; and &quot;The Guitar Man&quot;",
correct_answer: "Bread",
incorrect_answers: [
"America",
"Chicago",
"Smokie",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which American family band had a 1986 top 10 hit with the song &#039;Crush On You&#039;?",
correct_answer: "The Jets",
incorrect_answers: [
"DeBarge",
"The Jacksons",
"The Cover Girls",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Who had a 1976 hit with the song &#039;You Make Me Feel Like Dancing&#039;?",
correct_answer: "Leo Sayer",
incorrect_answers: [
"Elton John",
"Billy Joel",
"Andy Gibb",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "hard",
question: "Which of these songs was released in 1996?",
correct_answer: "The Smashing Pumpkins - &quot;1979&quot;",
incorrect_answers: [
"Prince - &quot;1999&quot;",
"James Blunt - &quot;1973&quot;",
"David Bowie - &quot;1984&quot;",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "Who is the frontman of the band 30 Seconds to Mars?",
correct_answer: "Jared Leto",
incorrect_answers: [
"Gerard Way",
"Matthew Bellamy",
"Mike Shinoda",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "The song &quot;Twin Size Mattress&quot; was written by which band?",
correct_answer: "The Front Bottoms",
incorrect_answers: [
"Twenty One Pilots",
"The Wonder Years",
"The Smith Street Band",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "Which country does the band Rammstein hail from?",
correct_answer: "Germany",
incorrect_answers: [
"Austria",
"Armenia",
"Belgium",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "According to a Beatles song, who kept her face in a jar by the door?",
correct_answer: "Eleanor Rigby",
incorrect_answers: [
"Loretta Martin",
"Molly Jones",
"Lady Madonna",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which band released songs such as &quot;Electric Feel&quot;, &quot;Kids&quot;, and &quot;Time to Pretend&quot;?",
correct_answer: "MGMT",
incorrect_answers: [
"Passion Pit",
"Phoenix",
"Franz Ferdinand",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "In which city did American rap producer DJ Khaled originate from?",
correct_answer: "Miami",
incorrect_answers: [
"New York",
"Detroit",
"Atlanta",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "EDM producer Marshmello performs live wearing clothes and a marshmallow mask of what colour?",
correct_answer: "White",
incorrect_answers: [
"Black",
"Blue",
"Yellow",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "Finish these lyrics from the 2016 song &quot;Panda&quot; by Desiigner: &quot;I got broads in _______&quot;.",
correct_answer: "Atlanta",
incorrect_answers: [
"Savannah",
"Augusta",
"Marietta",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Madonna&#039;s song &quot;Hung Up&quot; includes a piece from which popular 70s song?",
correct_answer: "Gimmie! Gimmie! Gimme! (A Man After Midnight)",
incorrect_answers: [
"Staying Alive",
"Night Fever",
"The Chain",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which Toronto landmark was featured on the cover art of Canadian rapper Drake&#039;s 2016 album &quot;Views&quot;?",
correct_answer: "CN Tower",
incorrect_answers: [
"Allan Gardens",
"Union Station",
"Prince of Wales Theatre",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which of these artists has NOT been a member of dancehall group Major Lazer?",
correct_answer: "Skrillex",
incorrect_answers: [
"Diplo",
"Jillionaire",
"Walshy Fire",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "hard",
question: "What is the name of the 2016 mixtape released by Venezuelan electronic producer Arca?",
correct_answer: "Entra&ntilde;as",
incorrect_answers: [
"&amp;&amp;&amp;&amp;&amp;&amp;",
"Sheep",
"Xen",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "hard",
question: "What is the British term for a 64th note?",
correct_answer: "Hemidemisemiquaver",
incorrect_answers: [
"Semihemidemisemiquaver",
"Semiquaver",
"Demisemiquaver",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "Which brass instrument has the lowest pitch in an orchestra?",
correct_answer: "Tuba",
incorrect_answers: [
"Trumpet",
"Saxophone",
"Trombone",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "hard",
question: "Which of these is NOT a song featured on the Lockjaw EP released in 2013 by Flume &amp; Chet Faker?",
correct_answer: "Left Alone",
incorrect_answers: [
"What About Us",
"This Song Is Not About A Girl",
"Drop The Game",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which artist collaborated with American DJ Dillon Francis to release the song 2016 &quot;Need You&quot;?",
correct_answer: "NGHTMRE",
incorrect_answers: [
"LOUDPVCK",
"KRNE",
"DVBBS",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "The &quot;K&quot; in &quot;K-Pop&quot; stands for which word?",
correct_answer: "Korean",
incorrect_answers: [
"Kenyan",
"Kazakhstan",
"Kuwaiti",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "What was Rage Against the Machine&#039;s debut album?",
correct_answer: "Rage Against the Machine",
incorrect_answers: [
"Evil Empire",
"Bombtrack",
"The Battle Of Los Angeles",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Pink Floyd made this song for their previous lead singer Syd Barrett.",
correct_answer: "Shine On You Crazy Diamond",
incorrect_answers: [
"Wish You Were Here",
"Have A Cigar",
"Welcome to the Machine",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "What is the relationship between the band members of American rock band King of Leon?",
correct_answer: "Brothers &amp; cousins",
incorrect_answers: [
"Childhood friends",
"Former classmates",
"Fraternity house members",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which of these is NOT a name of an album released by American rapper Pitbull?",
correct_answer: "Welcome to Miami",
incorrect_answers: [
"Dale",
"Global Warming",
"Armando",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "Which band released songs suchs as &quot;Rio&quot;, &quot;Girls on Film&quot;, and &quot;The Reflex&quot;?",
correct_answer: "Duran Duran",
incorrect_answers: [
"The Cure",
"New Order",
"Depeche Mode",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "The 2016 song &quot;Starboy&quot; by Canadian singer The Weeknd features which prominent electronic artist?",
correct_answer: "Daft Punk",
incorrect_answers: [
"deadmau5",
"Disclosure",
"DJ Shadow",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "From which country did the song &quot;Gangnam Style&quot; originate from?",
correct_answer: "South Korea",
incorrect_answers: [
"Japan",
"North Korea",
"China",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Who recorded the album called &quot;Down to the Moon&quot; in 1986?",
correct_answer: "Andreas Vollenweider",
incorrect_answers: [
"Jean-Michel Jarre",
"Bing Crosby",
"Enya",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "What collaborative album was released by Kanye West and Jay-Z in 2011?",
correct_answer: "Watch the Throne",
incorrect_answers: [
"Distant Relatives",
"What a Time to be Alive",
"Unfinished Business",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "What year was Red Hot Chill Pepper&#039;s album &quot;Californication&quot; released?",
correct_answer: "1999",
incorrect_answers: [
"1997",
"2000",
"1992",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which of these is not an Ed Sheeran album?",
correct_answer: "-",
incorrect_answers: [
"+",
"X",
"&divide;",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "&quot;Drink the Sea&quot; is an album by which electronic music artist?",
correct_answer: "The Glitch Mob",
incorrect_answers: [
"Avicii",
"XXYYXX",
"Flux Pavilion",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "hard",
question: "&quot;All the Boys&quot; by Panic! At the Disco was released as a bonus track on what album?",
correct_answer: "Too Weird To Live, Too Rare To Die!",
incorrect_answers: [
"A Fever You Can&#039;t Sweat Out",
"Death Of A Bachelor",
"Vices &amp; Virtues",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Cryoshell, known for &quot;Creeping in My Soul&quot; did the advertising music for what Lego Theme?",
correct_answer: "Bionicle",
incorrect_answers: [
"Hero Factory",
"Ben 10 Alien Force",
"Star Wars",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "What was the best selling album of 2015?",
correct_answer: "Adele, 25",
incorrect_answers: [
"Fetty Wap, Fetty Wap",
"Taylor Swift, 1989",
"Justin Bieber, Purpose",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Who is the lead singer of Bastille?",
correct_answer: "Dan Smith",
incorrect_answers: [
"Will Farquarson",
"Kyle Simmons",
"Chris Wood",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "Which song on Daft Punk&#039;s &quot;Random Access Memories&quot; features Pharrell Williams?",
correct_answer: "Get Lucky",
incorrect_answers: [
"Doin&#039; It Right",
"Instant Crush",
"The Game of Love",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "How many members are in the Japanese rock band SCANDAL?",
correct_answer: "4",
incorrect_answers: [
"5",
"2",
"18",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "African-American performer Sammy Davis Jr. was known for losing which part of his body in a car accident?",
correct_answer: "Left Eye",
incorrect_answers: [
"Right Ear",
"Right Middle Finger",
"Nose",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "In which year did &quot;Caravan Palace&quot; release their first album?",
correct_answer: "2008",
incorrect_answers: [
"2000",
"2015",
"2004",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "What was David Bowie&#039;s real surname?",
correct_answer: "Jones",
incorrect_answers: [
"Johnson",
"Edwards",
"Carter",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "hard",
question: "What was the name of the hip hop group Kanye West was a member of in the late 90s?",
correct_answer: "The Go-Getters",
incorrect_answers: [
"The Jumpers",
"The Kickstarters",
"The Beat-Busters",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "What is rapper Drake&#039;s real name?",
correct_answer: "Aubrey Graham",
incorrect_answers: [
"Shaun Carter",
"Dwayne Carter",
"Andre Young",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "The Who&#039;s eponymous line, &quot;Teenage Wasteland&quot;, appears in which of their songs?",
correct_answer: "Baba O&#039; Riley",
incorrect_answers: [
"The Seeker",
"Won&#039;t Get Fooled Again",
"Pinball Wizard",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Which artist or group did John Lennon consider &quot;son(s) of the Beatles&quot;?",
correct_answer: "Jeff Lynne&#039;s Electric Light Orchestra",
incorrect_answers: [
"The Rolling Stones",
"Pink Floyd",
"The Who",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "hard",
question: "Which lyric is about Red Hot Chili Peppers frontman Anthony Kiedis?",
correct_answer: "&quot;A rainy Lithuanian / Is dancing as an Indian&quot;",
incorrect_answers: [
"&quot;Fly away on, my zephyr / I feel it more than ever&quot;",
"&quot;And I liked the dimple in your chin / Your pale blue eyes&quot;",
"&quot;You used to be so warm and affectionate...but now you&#039;re quick to get into your regret&quot;",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "hard",
question: "What was the name of the cold-war singer who has a song in Grand Theft Auto IV, and a wall landmark in Moscow for his memorial?",
correct_answer: "Viktor Tsoi",
incorrect_answers: [
"Jimi Hendrix",
"Brian Jones",
"Vladimir Vysotsky",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "easy",
question: "The band Muse released their first album, Showbiz, in what year?",
correct_answer: "1999",
incorrect_answers: [
"1998",
"2000",
"2001",
],
},
{
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Who performed the guitar solo on Michael Jackson&#039;s hit &quot;Beat It&quot;?",
correct_answer: "Eddie Van Halen",
incorrect_answers: [
"Steve Vai",
"Kirk Hammett",
"Zakk Wylde",
],
},
]


question_hash = {
category: "Entertainment: Music",
type: "multiple",
difficulty: "medium",
question: "Who performed the guitar solo on Michael Jackson&#039;s hit &quot;Beat It&quot;?",
correct_answer: "Eddie Van Halen",
incorrect_answers: [
"Steve Vai",
"Kirk Hammett",
"Zakk Wylde",
],
}


# when in CLI
# - puts HTMLEntities.new.decode <value> to prevent encodes from showing 
